baseurl = "/"
languageCode = "en-us"
title = "Reticent Random Rants"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-124346031-1"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "by owsega (a human also known as Gabriel Owoeye)"
  cover = "images/cover.jpg"
  author = "Gabriel Owoeye"
  authorlocation = "Lagos, Nigeria"
  authorwebsite = "https://owse.ga"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-124346031-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "https://feeds.feedburner.com/ReticentRandomRants"
  githubName = "owsega"
  twitterName = "OwSeGa001"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "OwSeGa001"
